// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxvvgscbizhcnyoifjcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4dnZnc2NiaXpoY255b2lmamNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NzczMTAsImV4cCI6MjA3NDE1MzMxMH0.A7kGG7d9ND8isXOAqcV7rO0PaD9AqnyDXDSzdfPaBO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});